#include "test_helpers.hpp"

TEST(Column, Select) {
  Table tbl = Table::FromRaw("foo");
  Column name{"name", "TEXT"};
  Column age{"age", "BIGINT"};

  EXPECT_EQ(From(tbl).Select({name, age}).ToString(),
            "SELECT name, age FROM foo");
}

TEST(Column, As) {
  Table tbl = Table::FromRaw("foo");
  Column name{"name", "TEXT"};

  auto bar = "bar";
  EXPECT_EQ(From(tbl.As(bar)).Select(Expr::FromRaw(bar).Dot(name)).ToString(),
            "SELECT bar.name FROM foo AS bar");
}

TEST(Column, Compare) {
  Column age{"age", "BIGINT"};

  EXPECT_EQ((age < 18).ToString(), "age < 18");
  EXPECT_EQ((age <= 18).ToString(), "age <= 18");
  EXPECT_EQ((age > 18).ToString(), "age > 18");
  EXPECT_EQ((age >= 18).ToString(), "age >= 18");
  EXPECT_EQ((age == 18).ToString(), "age = 18");
  EXPECT_EQ((age != 18).ToString(), "age != 18");
}

TEST(Column, ToExpr) {
  Column age{"age", "BIGINT"};

  EXPECT_EQ(age.ToExpr().IsNull().ToString(), "age IS NULL");
  EXPECT_EQ(age.ToExpr().Between(0, 18).ToString(), "age BETWEEN 0 AND 18");
  EXPECT_EQ((age.ToExpr() + 1).ToString(), "age + 1");
}

TEST(TableWithColumns, Simple) {
  Column name{"name", "TEXT"};
  Column age{"age", "BIGINT"};
  TableWithColumns tbl = TableWithColumns::FromRaw("foo", {name, age});

  EXPECT_EQ(From(tbl).Select(tbl.SelectArgAll()).ToString(),
            "SELECT name, age FROM foo");
}

TEST(TableWithColumns, AsAndDotSelfJoin) {
  Column name{"name", "TEXT"};
  TableWithColumns users = TableWithColumns::FromRaw("users", {name});
  TableWithColumns lhs = users.As("lhs");
  TableWithColumns rhs = users.As("rhs");

  EXPECT_EQ(From(Join(lhs, rhs, Inner()).On(lhs.Dot(name) == rhs.Dot(name)))
                .Select(lhs.Dot(name).As("name"))
                .ToString(),
            "SELECT lhs.name AS name FROM users AS lhs INNER JOIN "
            "users AS rhs ON lhs.name = rhs.name");
}

TEST(TableWithColumns, DotRejectsUnknownColumn) {
  Column name{"name", "TEXT"};
  Column age{"age", "BIGINT"};
  TableWithColumns users = TableWithColumns::FromRaw("users", {name}).As("u");

  EXPECT_EQ(users.Dot(name).ToString(), "u.name");
  EXPECT_THROW(Ignore(users.Dot(age)), std::invalid_argument);
  EXPECT_THROW(Ignore(users.Dot("nonexistent")), std::invalid_argument);
}

TEST(TableWithColumns, DotRequiresAsFirst) {
  Column name{"name", "TEXT"};
  TableWithColumns users = TableWithColumns::FromRaw("users", {name});

  EXPECT_THROW(Ignore(users.Dot(name)), std::logic_error);
}

TEST(TableAlias, Dot) {
  TableAlias alias = TableAlias::From("bar");
  Column name{"name", "TEXT"};

  EXPECT_EQ(alias.Dot("name").ToString(), "bar.name");
  EXPECT_EQ(alias.Dot(name).ToString(), "bar.name");
}

TEST(TableAlias, DotUsableDirectlyAsExprNoFromRawNeeded) {
  Table users = Table::FromRaw("users");
  TableAlias lhs = TableAlias::From("lhs");
  TableAlias rhs = TableAlias::From("rhs");
  Column name{"name", "TEXT"};

  EXPECT_EQ(From(Join(users.As("lhs"), users.As("rhs"), Inner())
                     .On(lhs.Dot(name) == rhs.Dot(name)))
                .Select(lhs.Dot(name).As("name"))
                .ToString(),
            "SELECT lhs.name AS name FROM users AS lhs INNER JOIN "
            "users AS rhs ON lhs.name = rhs.name");
}

TEST(TableAlias, InvalidNameThrows) {
  EXPECT_THROW(Ignore(TableAlias::From("not an identifier")),
               std::invalid_argument);
  EXPECT_THROW(Ignore(TableAlias::From("")), std::invalid_argument);
}

TEST(Column, ImplicitlyConvertsToExpr) {
  // Column::operator Expr() must stay non-explicit: a Column has to be
  // usable wherever a `const Expr &` parameter is expected, with no cast.
  Column age{"age", "BIGINT"};
  EXPECT_EQ(Expr::FromRaw("x").Between(age, 30).ToString(),
            "x BETWEEN age AND 30");
}

// Example of autogenerated declarations
// Table "users"
namespace users {

// Fields
const Column kName{"name", "TEXT"};
const Column kAge{"age", "BIGINT"};

// Explicit fields enumeration ("*" replacement)
const std::vector<Column> kAll = {
    kName,
    kAge,
};

// The table itself
const TableWithColumns kTable = TableWithColumns::FromRaw("users", kAll);

// TODO: unable to create table fields with name "table" or "all", hmm...

} // namespace users
